-- phpMyAdmin SQL Dump
-- version 3.5.8.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jun 23, 2013 at 03:51 PM
-- Server version: 5.5.29-log
-- PHP Version: 5.3.24

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `joomlavi_karaoke`
--

-- --------------------------------------------------------

--
-- Table structure for table `list`
--

CREATE TABLE IF NOT EXISTS `list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenbh` varchar(255) NOT NULL,
  `mabh` int(11) DEFAULT NULL,
  `casi` varchar(255) DEFAULT NULL,
  `nhacsi` varchar(255) DEFAULT NULL,
  `member` varchar(255) DEFAULT NULL,
  `loibh` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=41 ;

--
-- Dumping data for table `list`
--

INSERT INTO `list` (`id`, `tenbh`, `mabh`, `casi`, `nhacsi`, `member`, `loibh`) VALUES
(20, 'Gọi Tên Em Trong Đêm', 0, 'The Men', 'Nhạc Hoa lời Việt', '', 'Đêm nghe hạt mưa rơi lòng chợt nhớ em vô cùng\r\nChuyện Tình ngày ấy k sao quên đc\r\nGiờ 2 ta ở 2 nơi lòng người có nghĩ đến bao giờ\r\nLúc trước anh ra đi là có lý do\r\nNếu biết trước tương lai anh đã chẳng yêu em\r\nNhưng con tim anh đây thật k sao quên đc em người ơi\r\nNước mắt đã rơi vì nhớ em mong em trong từng đêm vắng\r\nMong cho em luôn được hạnh phúc nơi phương trời xa\r\nGọi tên em trong đêm trái tim này xót xa\r\nNgười yêu ơi hãy quên những năm tháng êm đềm hôm nào\r\nGọi tên em trong đêm để mình anh chịu nỗi đắng cay\r\nMột thế giới khác mang anh đi chẳng thể nào có em\r\nGọi tên trong đêm\r\nsẽ chẳng thể có nhau\r\ntình duyên ta thế thôi chắc có lẽ đã đc ăn bài\r\ngọi tên em trong đêm để mình anh chịu nỗi đớn đau\r\nmột thế giới khác mang anh đi chia đôi tình chúng ta cách xa 2 phương trời\r\nmong em qua bao đêm\r\ntrái tim này xót xa\r\nngười ơi yêu ơi hãy quên tình nồng say từng năm tháng\r\nGọi tên trong đêm\r\nđể mình anh chịu nỗi đắng cay\r\nmột thế giới khác mang anh đi chẳng thể nào có em\r\nGọi tên trong đêm\r\nsẽ chẳng thể có nhau\r\ntình duyên ta thế thôi chắc có lẽ đã đc ăn bài\r\ngọi tên em trong đêm để mình anh chịu nỗi đớn đau\r\nmột thế giới khác mang anh đi chia đôi tình chúng ta cách xa 2 phương trời. '),
(21, 'Giấc Mơ Cha Pi', 0, 'Y Moan', 'Trần Tiến', '', 'Ở nơi ấy, tôi đã thấy trên ngọn núi cao có hai người, chỉ có hai người yêu nhau. . . .\r\nHọ đã sống không mùa đông, không mùa nắng, mưa. có một mùa, chỉ có một mùa yêu nhau. . . .\r\nỞ nơi ấy, đàn dê trắng nhởn nhơ trên đồi, một mái tranh nghèo, một nhà sàn đơn sơ.\r\nỞ nơi ấy, họ đã sống cuộc sống yên bình. Ai nghèo cũng có cây đàn ChaPi.\r\nKhi rung lên, từng sợi dây đàn đã đong đầy hồn người Đak-lay.\r\n\r\nƠi Đak-lay, ơi rừng cây ngọn núi vang tiếng đàn ChaPi\r\nAi yêu tự do, yêu rừng xanh thì lên núi nghe đàn ChaPi\r\nTôi yêu ChaPi không còn cô đơn, không buồn, không vui.\r\nKhi nghe ChaPi chợt thấy nao lòng một giấc mơ\r\nÔi ChaPi. '),
(22, 'Tiếng Gió Xôn Xao', 0, ' Đàm Vĩnh Hưng', '', '', 'Gió vẫn hát thì thầm đến bên tôi như thật gần\r\nGió muốn nói điều gì tha thiết\r\nGió vẫn nhắc một người đã ra đi không trở lại\r\nLỡ mất chuyện tình không thể quên\r\nBước những chuỗi ngày dài ấp ôm bao đêm huyền diệu\r\nÁnh mắt ấy giờ này xa lắm\r\nThoáng phút chốc giật mình ngỡ như em đang thật gần\r\nGió đánh thức vì tôi ngủ mê\r\nThắp ánh sáng bước qua đêm thâu\r\nChờ mong ngày mai khát vọng\r\nVà gió vẫn thế gió mang tôi đi tìm em\r\nDẫu có lúc nước mắt tuôn rơi\r\nNhư hạt sương, hạt sương bé nhỏ\r\n\r\nGió sẽ hát rì rào\r\nGió ru tim tôi ngày ngày mãi xôn xao '),
(23, 'Tôi Là Ai Em Là Ai', 0, 'Kasim Hoàng Vũ', '', '', 'Đêm qua tôi nằm mơ thấy em,\r\nTrong giấc mơ em là của ai\r\nĐêm qua em nằm mơ thấy tôi,\r\nNhưng giấc mơ không phải là tôi\r\n\r\nTôi yêu em, từng đêm nhớ em\r\nTôi lang thang để được gần em\r\nTôi không tin rằng trong giấc mơ,\r\nEm bên ai không phải là tôi\r\n\r\nEm dịu dàng như tia sáng trong đêm,\r\nĐem yêu thương phủ lên trên cuộc đời\r\nTôi ngập ngừng bước đến bên em,\r\nÔi bỗng nhiên sao em lại tan biến\r\n\r\nMưa thì thầm như anh nói yêu em\r\nEm đưa tay đón cơn mưa vào lòng\r\nNhưng đừng là giấc mơ đêm qua\r\nTôi cho em nụ hôn ban đầu\r\n\r\nTôi là ai mà cứ mãi yêu em\r\nEm là ai mà cứ mãi yêu tôi '),
(24, ' Vì Yêu ', 0, 'Kasim Hoàng Vũ', '', '', 'Nắm tay nhau trên đường tung tăng vui ca ngày tháng\r\nDấu chân xưa ghi lại đôi ta yêu nhau ngày ấy\r\nTóc em xanh vì anh, mắt anh vui vì em\r\nChung bước vì yêu.\r\n\r\nBiết em yêu anh nhiều đôi khi anh hay lạc lối\r\nGió đưa anh quay về cùng em trong đêm mịt tối\r\nMắt môi xưa còn đây\r\nChiếc hôn nay vụt bay\r\nBay xa tầm tay.\r\n\r\nYêu dù là xa ở nơi đâu anh xin được yêu\r\nXa dù thật xa nếu đôi ta yêu nhau thật sâu\r\nMuôn nghìn trùng không chia cách\r\nđôi mình cùng yêu nhau mãi\r\nVới em vì tình yêu anh sẽ...\r\n\r\nChờ em xa vòng tay và thứ tha cho anh ngày ấy\r\nNơi đây mình anh tìm bóng em như chim lạc lối\r\nNgày chờ, đêm khóc mưa trong lòng giông tố\r\nDứt mưa sao chưa dứt nỗi buồn? '),
(25, 'Đứa Bé', 0, '', 'Minh Khang', '', 'Trong đêm một bàn chân bước\r\nBé xíu lang thang trên đường\r\nÁnh mắt buồn, mệt nhoài của em\r\nEm rất buồn vì em không biết đi, đi về đâu\r\n\r\nCuộc sống mưu sinh chỉ làm em qua cơn đói từng ngày\r\nVì em không cha, vì em đã mất mẹ\r\nThương đau vẫn là đau thương\r\n\r\nEm mơ một vì sao sáng\r\nDẫn lối em trên đường đời\r\nDẫu biết rằng chỉ là giấc mơ\r\nĐã lâu rồi em đã không, không có tình thương\r\n\r\nNhìn thấy ai ai cũng đều vui bên mẹ cha\r\nGiọt lệ em tuôn rơi, hòa tan với nỗi buồn\r\nBước đi trong chiều mưa\r\n\r\nHãy lau khô cuộc đời em\r\nBằng tình thương, lòng nhân ái của con người\r\nVà hãy lau khô giọt nước mắt trong lòng em\r\nBằng tất cả trái tim con người Việt Nam... '),
(26, 'Nỗi lòng xa xứ', 0, 'Nguyễn Phi Hùng', '', '', 'Một mình nơi đây nhớ thương chốn quê nhà\r\nCuộc đời công nhân bao bồn bề âu lo\r\nTa tìm gì đây giữa xa hoa thị thành\r\nLùa vội chén cơm cho kịp giờ tan ca\r\nPhòng trọ đơn sơ bữa cơm với dưa cà\r\nBạn bè quanh ta bao mọi miền quê xa\r\nLưu lạc về đây sống tha phương từng ngà\r\nVận đời nỗi trôi theo dòng đời mưu sinh\r\nThương mẹ cha đang mong chờ con từng giờ\r\nThương đàn em thơ ngây vang tiếng cười đùa\r\nMưa lũ tràn về trắng xóa cánh đồng xanh\r\nMái nhà yên ấm bông hoa mỏng manh\r\nMong một mai cơn giống tố sẽ dần qua\r\nChút tiền lương bao năm con gửi về nhà\r\nMong gia đình mình được sống an vui\r\nNỗi lòng xa xứ chẳng thẻ nào nguôi.'),
(27, 'Tôn thờ một tình yêu', 0, 'Bằng Cường - Khánh Phương', 'Bằng Cường', '', 'Từng năm tháng vô tình vì người yêu dối gian mình\r\nCó lúc con tim ta như lặng thinh\r\nNgười cất bước ra đi, từng đêm ta khóc chia ly\r\nBiết đến bao lâu ta thôi mộng mơ.\r\n\r\nLòng ta mãi tôn thờ tình yêu này đến bao giờ\r\nDẫu biết em nay không quay về đây.\r\n(Dẫu biết nay em sẽ không về đây.)\r\nNhiều khi muốn hỏi lòng: tại sao ta mãi hy vọng\r\nƯớc muốn bên em ta như ngày xưa.\r\n\r\nTình tan vỡ thôi từ đây ân tình cũng như làn mây\r\nCứ trôi hoài cứ phiêu du như tình em xa mãi.\r\nTình tan vỡ thôi người ơi, nhớ làm gì và chờ gì nữa\r\nThế nhưng sao lòng vẫn không thể quên được người.\r\n\r\nNgười yêu hỡi bao lệ rơi lúc đêm về lặng thầm cay đắng\r\nChỉ riêng anh bước đơn côi thà nước mắt rơi từng đêm.\r\n(Chỉ riêng anh bước đơn côi trong từng đêm hoang vắng.)\r\nNgười yêu hỡi sao lòng anh mãi không quên dù tình đã hết\r\nCứ trông mong, cứ yêu thương về em. '),
(31, 'Cầu Vồng Sau Mưa', 0, 'Cao Thái Sơn', 'Nguyễn Văn Chung', '', 'Đứng giữa con đường mưa anh vô tình nhớ một nụ cười\r\nĐứng giữa con đường mưa anh vô tình nhớ một vòng tay\r\nNhững kỷ niệm ngày xưa thôi mong chờ cũng thôi hy vọng\r\nĐã có khi tưởng như trái tim này cũng thôi mộng mơ.\r\nNhưng rồi anh tìm thấy những kỷ niệm từ khi gặp em\r\nNhưng rồi anh tìm thấy những nụ cười cho anh niềm vui.\r\nTạm biệt nhé những nỗi đau ơi\r\nTạm biệt nhé nỗi nhớ một thời\r\nVì có em, anh chỉ cần 1 vòng tay ấm ôm lấy anh.\r\nĐể ngày mai anh biết yêu hơn\r\nNiềm hạnh phúc mới đến dịu êm\r\nCám ơn em vì đã cho anh một tình yêu..! '),
(32, 'Kiếp Đỏ Đen', 0, 'Duy Mạnh', 'Duy Mạnh', '', 'Giờ ta chẳng còn chi, mãi trắng tay mà thôi.\r\nĐầu bạc, răng long, phũ phàng.\r\nTiền có kiếm như nước rồi cũng sẽ trôi hết.\r\nTay không trắng tay lại về không.\r\nĐời phiêu lưu là thế không biết đâu ngày mai, nên giờ đây mới đắng cay.\r\nNgồi trước tấm gương sáng rọi vào đó mới thấy thân xác hoang tàn không nhận ra.\r\nTa mang bao tội lỗi nên thân ta giờ đây, kiếp sống không nhà, không người thân.\r\nTa mang bao tôi lỗi, người ơi ta đâu còn chi xin hãy tránh xa kiếp đỏ đen '),
(33, 'Một thời đã xa', 0, 'Đàm Vĩnh Hưng', '', '', 'Đừng buồn anh hỡi khi lỡ nói yêu em rồi\r\nBận lòng chi nữa hỡi anh xin hãy quên em đi\r\nGiây phút bên nhau anh sẽ quên mau\r\nChỉ có em thôi giữ mãi bóng hình xưa\r\nĐời ai cũng có giây phút trót yêu dại khờ\r\nVà em đã biết biết anh sẽ chẳng yêu em đâu\r\nEm sẽ không quên giây phút bên nhau\r\nEm đã trao anh trao anh nụ hôn ấy\r\n\r\nVà em biết anh sẽ quên hết\r\nNhững bài tình ca viết riêng tặng em\r\nVà em biết trái tim anh có hình bóng ai kia đâu chỉ riêng em\r\nVà em sẽ không trách anh nữa\r\nChẳng trách anh đâu\r\nKhi ta đến bên nhau tình gian dối .\r\n\r\nVà em biết anh sẽ quên hết những bài tình ca viết riêng tặng em\r\nVà em biết trái tim anh có hình bóng ai kia đâu chỉ riêng em\r\nVà em sẽ không trách anh nữa\r\nChẳng trách anh đâu\r\nKhi ta đến bên nhau\r\nTình yêu dối lừa . '),
(34, 'Giây phút chia xa', 0, 'Duy Mạnh', '', '', 'Giờ chia tay nhau đã đến\r\nCòi tàu thét vang trong màn đêm\r\nHãy hôn nhau đi lần cuối\r\nGiòng lệ tuôn rơi mặn đắng\r\nNgẹn ngào xiết đôi bàn tay\r\nLòng ta nghe sao lạnh giá\r\n\r\nĐoàn tàu lăn bánh rời bến\r\nChầm chậm khuất xa dần xa\r\nĐã đưa em đi người hỡi\r\nĐể lại con tim đau nhói\r\nLõi loi bước đi giữa màn đêm\r\nGiòng lệ vẫn mãi tuôn trào\r\n\r\nThời gian trôi qua thật mau\r\nGiờ tàu biết đi về đâu ?\r\nNụ hôn yêu thương còn ấm môi\r\nMà em đã ra đi về nơi phương xa người hỡi\r\n\r\nDù cho xa nhau mãi mãi\r\nTình anh vẫn trao về em\r\nTừ trong con tim vẫn mong chờ\r\nRồi mai đây em sẽ quay trở về .. '),
(35, 'Hết Rồi', 0, 'Đàm Vĩnh Hưng', '', '', 'Một ngày em đi đến nơi xa vời xóa hết bao buồn thương.\r\nmột thời bên nhau ái ân nồng xay, giờ tìm hoài không thấy .\r\nNgười yêu ơi em nỡ quên sao đành,\r\nTình tôi bơ vơ trái tim giá lạnh\r\nNhớ em một mình đi mãi.\r\n\r\nNhìn thời gian trôi tháng năm mong chờ dưới bóng đêm lẻ loi.\r\nNgồi đây tôi mơ giấc mơ bình yên được trọn đời bên em.\r\nTrời xanh bao la hỡi em nơi nào,\r\nMình tôi lang thang gió mưa thét gào\r\nBiết là giấc mơ xa vời.\r\n\r\nBao đam mê ngày xưa cũng đi qua rồi,\r\nTrong con tim đầy vơi bóng em mà thôi.\r\nGiờ còn chi nữa đâu vì em thay đổi\r\nMột cuộc tình ấm êm ai ngờ gian rối.\r\nEm cho tôi buồn đau biết bao đêm rồ,\r\nNay em quay về đây muốn ta thành đôi.\r\nVề đi thôi hỡi em đừng nên tiếc nuối\r\nChuyện tình mình đã bay theo làn sương khói'),
(36, ' Lợi Danh', 0, 'Phạm Khánh Hưng', 'Phạm Khánh Hưng', '', 'Dòng đời trôi qua thật nhanh\r\nCuộc sống đua trên câu Lợi Danh\r\nLòng cứ ngỡ khi ta giàu sang sẽ không ưu phiền\r\nTừng ngày qua tâm hồn ta chôn vùi trong ý nghĩa bạc vàng\r\nNên không tin vào ai, thật lòng với ai.\r\n\r\nRồi nay khi ta đã có được những chi trong ta hằng mong\r\nCàng lìa xa đi bao tình thân đã yêu thương ta\r\nChẳng cần ai, không cần ai! Tiền sẽ mua cho ta niềm vui\r\nNên đời ta chỉ biết sống cho riêng mình.\r\n\r\nĐK:\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nĐể giờ đây ta đang nhìn ta như người xa lạ\r\nCuộc sống ganh đua đổi thay chính ta\r\nNhạt mờ đi theo bao ngày qua lương tâm của ta.\r\n\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nNhìn lại ta quanh ta giờ đây hiu quạnh riêng mình\r\nTiền có cho ta trọn vẹn chữ vui ?\r\nHay chỉ làm ta thêm chẳng tin những ai gần ta.\r\n\r\nThời gian vẫn cứ đi mãi\r\nĐời nỗi trôi theo bao được thua\r\nĐể hôm nay khi câu Lợi Danh đã không vững bền\r\nGiàu mà chi ? Sang mà chi ? Rồi có ai đau thương vì ta ?\r\nNay mình ta chua xót, khóc cho thân mình ! '),
(37, 'Lợi Danh', 0, 'Phạm Khánh Hưng', 'Phạm Khánh Hưng', '', 'Dòng đời trôi qua thật nhanh\r\nCuộc sống đua trên câu Lợi Danh\r\nLòng cứ ngỡ khi ta giàu sang sẽ không ưu phiền\r\nTừng ngày qua tâm hồn ta chôn vùi trong ý nghĩa bạc vàng\r\nNên không tin vào ai, thật lòng với ai.\r\n\r\nRồi nay khi ta đã có được những chi trong ta hằng mong\r\nCàng lìa xa đi bao tình thân đã yêu thương ta\r\nChẳng cần ai, không cần ai! Tiền sẽ mua cho ta niềm vui\r\nNên đời ta chỉ biết sống cho riêng mình.\r\n\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nĐể giờ đây ta đang nhìn ta như người xa lạ\r\nCuộc sống ganh đua đổi thay chính ta\r\nNhạt mờ đi theo bao ngày qua lương tâm của ta.\r\n\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nNhìn lại ta quanh ta giờ đây hiu quạnh riêng mình\r\nTiền có cho ta trọn vẹn chữ vui ?\r\nHay chỉ làm ta thêm chẳng tin những ai gần ta.\r\n\r\nThời gian vẫn cứ đi mãi\r\nĐời nỗi trôi theo bao được thua\r\nĐể hôm nay khi câu Lợi Danh đã không vững bền\r\nGiàu mà chi ? Sang mà chi ? Rồi có ai đau thương vì ta ?\r\nNay mình ta chua xót, khóc cho thân mình ! '),
(40, 'Được và mất', 0, 'Lâm Hùng', '', '', 'Hoi nhan the con tin ai nua ko .\r\nkhi niem tin gan xa noi cuoi troi\r\nnguoi doi thay trang den ko doan dc\r\nbao loi noi chi trot luoi dau moi\r\nko la chi tinh than luon vay quanh\r\nchut loi danh dan chia 2 con nguoi\r\nduoc va mat may ai tu hieu minh\r\ntien la giay cach chia doi nghia tinh\r\n\r\nCao sang thap hen duyen so nao biet ai vuong mang\r\nhon nhau la nghia nhan trong moi nguoi\r\ndoi dau chi la the , cuoi doi dau chi la the\r\nai ko tro ve mo dat sau\r\n\r\nThe thai nhan tinh doi thay bang nhung cau chua cay\r\nhon thua la chu nhan de luu doi\r\ndoi khi co duoc mat , so troi cho ta ma thoi\r\nko ai gianh lay duoc dau ');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
